"""empty message

Revision ID: 006cae916f41
Revises: de8ee1cf1311
Create Date: 2021-02-02 12:19:52.628940

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '006cae916f41'
down_revision = 'de8ee1cf1311'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traveler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('password', sa.String(length=15), nullable=False),
    sa.Column('avatar', sa.String(length=180), nullable=True),
    sa.Column('rol', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('trip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_traveler', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('post_date', sa.DateTime(), nullable=False),
    sa.Column('needs_trip', sa.String(length=60), nullable=False),
    sa.Column('destination', sa.String(length=200), nullable=False),
    sa.Column('first_day', sa.Date(), nullable=False),
    sa.Column('last_day', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('receiving_offers', sa.Boolean(), nullable=False),
    sa.Column('counter', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_traveler'], ['traveler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('offers', sa.Column('id_trip', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'offers', 'trip', ['id_trip'], ['id'])
    op.drop_column('offers', 'counter')
    op.drop_column('userpro', 'avatar')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userpro', sa.Column('avatar', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('offers', sa.Column('counter', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'offers', type_='foreignkey')
    op.drop_column('offers', 'id_trip')
    op.drop_table('trip')
    op.drop_table('traveler')
    # ### end Alembic commands ###
