"""empty message

Revision ID: 3cc2db5b6310
Revises: c88f4c468f85
Create Date: 2021-02-16 20:14:46.317379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cc2db5b6310'
down_revision = 'c88f4c468f85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('attached', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offers', 'attached')
    # ### end Alembic commands ###
