"""empty message

Revision ID: 5b772291f0b6
Revises: 9468ca678f45
Create Date: 2021-03-14 11:49:59.278332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b772291f0b6'
down_revision = '9468ca678f45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('id_users', sa.String(length=20), nullable=False))
    op.create_unique_constraint(None, 'reviews', ['id_users'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='unique')
    op.drop_column('reviews', 'id_users')
    # ### end Alembic commands ###
