"""empty message

Revision ID: a96fbfe285c3
Revises: 8cdc8c0a5b7c
Create Date: 2021-01-23 09:44:56.632129

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a96fbfe285c3'
down_revision = '8cdc8c0a5b7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traveler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('password', sa.String(length=15), nullable=False),
    sa.Column('avatar', sa.String(length=200), nullable=True),
    sa.Column('rol', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('trip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_traveler', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('post_date', sa.DateTime(), nullable=False),
    sa.Column('needs_trip', sa.String(length=60), nullable=False),
    sa.Column('destination', sa.String(length=200), nullable=False),
    sa.Column('first_day', sa.Date(), nullable=False),
    sa.Column('last_day', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('receiving_offers', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_traveler'], ['traveler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('viaje')
    op.drop_index('email', table_name='viajero')
    op.drop_index('username', table_name='viajero')
    op.drop_table('viajero')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('viajero',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('avatar', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('rol', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('fecha_registro', mysql.DATETIME(), nullable=False),
    sa.CheckConstraint('(`is_active` in (0,1))', name='viajero_chk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('username', 'viajero', ['username'], unique=True)
    op.create_index('email', 'viajero', ['email'], unique=True)
    op.create_table('viaje',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_viajero', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('fecha_publicacion', mysql.DATETIME(), nullable=False),
    sa.Column('needs_trip', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('destination', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('first_day', sa.DATE(), nullable=False),
    sa.Column('last_day', sa.DATE(), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.CheckConstraint('(`is_active` in (0,1))', name='viaje_chk_1'),
    sa.ForeignKeyConstraint(['id_viajero'], ['viajero.id'], name='viaje_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('trip')
    op.drop_table('traveler')
    # ### end Alembic commands ###
